/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptcJogoDaVelha;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static ptcJogoDaVelha.Conexao.con;

/**
 *
 * @author samue
 */
public class tDefinirJogadores extends javax.swing.JFrame {

    public static class Variaveis
    {
        public static int vitoriasJogador1 = 0;
        public static int vitoriasJogador2 = 0;
        public static String nomeJogador1 = "";
        public static String nomeJogador2 = "";
    }
        
    /**
     * Creates new form tDefinirJogadores
     */
    public tDefinirJogadores() {
        initComponents();
        Conexao.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfJogador1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfJogador2 = new javax.swing.JTextField();
        btnJogar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogadores ");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Definir Jogadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Jogador 1:");

        tfJogador1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome do Jogador 2:");

        tfJogador2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnJogar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnJogar.setText("Começar a Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJogador1)
                            .addComponent(tfJogador2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 207, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnJogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        String sql = "", nomeJogador1,nomeJogador2;
        nomeJogador1 = tfJogador1.getText().toUpperCase();
        nomeJogador2 = tfJogador2.getText().toUpperCase();
        boolean acheiJogador1 = false;
        boolean acheiJogador2 = false;
             
        try{
            if(nomeJogador1.equals("") || nomeJogador2.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Escreva o nome dos jogadores corretamente!"," ERRO",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                sql = "SELECT * FROM jogadores where NomeJogador='" + nomeJogador1 + "' OR NomeJogador='" + nomeJogador2 + "'";
                Statement stm = con.prepareStatement(sql);
                stm.execute(sql);
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next())
                {
                    if ( rs.getString("NomeJogador").toUpperCase().equals(nomeJogador1))
                    {
                        Variaveis.vitoriasJogador1 = Integer.parseInt(rs.getString("NumVitoria"));
                        Variaveis.nomeJogador1 =  rs.getString("NomeJogador");
                        acheiJogador1 = true;
                    }
                    else if ( rs.getString("NomeJogador").toUpperCase().equals(nomeJogador2))
                    {
                        Variaveis.vitoriasJogador2  = Integer.parseInt(rs.getString("NumVitoria"));
                        Variaveis.nomeJogador2 =  rs.getString("NomeJogador");
                        acheiJogador2 = true;
                    }
                }

                if(!acheiJogador1)
                {
                    sql="INSERT INTO Jogadores (NomeJogador, NumVitoria) values ('" + nomeJogador1 +"',0 )";
                    stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    Variaveis.vitoriasJogador1 = 0;
                    Variaveis.nomeJogador1 =  nomeJogador1;
                }
                
                if(!acheiJogador2)
                {
                    sql="INSERT INTO Jogadores (NomeJogador, NumVitoria) values ('" + nomeJogador2 +"',0 )";
                    stm = con.prepareStatement(sql);
                    stm.execute(sql);
                   
                    Variaveis.vitoriasJogador2 = 0;
                    Variaveis.nomeJogador2 =  nomeJogador2;
                }
                
                tJogo tJogo = new tJogo();
                tJogo.setVisible(true);
                this.setVisible(false);
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao incluir, tente novamente" + e,"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try{
            Conexao.con.close();
        }
        catch (Exception e){
            System.out.println(e);
        }
        System.exit(0);    
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tDefinirJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tDefinirJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tDefinirJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tDefinirJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tDefinirJogadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfJogador1;
    private javax.swing.JTextField tfJogador2;
    // End of variables declaration//GEN-END:variables
}
